steps:
  - name: "gcr.io/cloud-builders/go"
    args: ["install", "github.com/skim1420/mdservice"]
    env: ["PROJECT_ROOT=github.com/skim1420/mdservice"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "us.gcr.io/bbb-feo-77124/mdservice:$REVISION_ID", "-f", "Dockerfile", "."]
images:
  - "us.gcr.io/bbb-feo-77124/mdservice:$REVISION_ID"
