steps:
  - name: "gcr.io/cloud-builders/go"
    args: ["install", "github.com/skim1420/mdservice"]
    env: ["PROJECT_ROOT=github.com/skim1420/mdservice"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/spinnaker-1022/mdservice:$REVISION_ID", "-f", "Dockerfile", "."]
images:
  - "gcr.io/spinnaker-1022/mdservice:$REVISION_ID"
